### ISSUE TITLE
Documents: Export to a static website

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#175]
Maybe we do this as a git commit to a jekyll site on github pages.

- [ ] Authenticate against a github account
- [ ] Choose, or create, a gh-pages website
- [ ] Allow documents to be snapshotted, with annotations, as posts
- [ ] Make the default layout include a simple viewer, with support for annotations
